#!/bin/bash

# auto-generate header file to pass arguments to user project via Makefile
#   * create argv array with program name, provided USER_ARG, and a random arg
#   * uses SRANDOM for prng and simple bash functions for file output
#   * called by Makefile as `util/gen_argv.sh $(U_COMMON_INC_DIR)/usr_arg.h $(USER_ARG)`

if [[ $# < 1 ]]; then
    echo "illegal script usage, aborting..."
    exit 1
fi

args=("736051737873545250" "i2c_has_2_wires" "clear_your_event_flags" "0xfeedfacebeefcafe")

argc=$(($# + 1))
filename=$1
shift
uarg=
for uargi in "$@"; do
    uarg+="\"$uargi\""
    uarg+=", "
done

rn=$((SRANDOM % ${#args[@]}))
uarg+="\"${args[$rn]}\""

echo '/**  **  **  **  **  **  **THIS FILE WAS AUTOGENERATED**  **  **  **  **  **  **/' > $filename
echo 'char *user_argv[] = {"main", '$uarg', NULL};' >> $filename
echo 'int user_argc = '$argc';' >> $filename
echo '/**  **  **  **  **  **  **  **  **  **   **  **  **  **  **  **  **  **  **  **/' >> $filename
